### ISSUE TITLE
Open with option Does not work

### ISSUE THREAD

**Issue by kazi-10g80d** [ed10vi/fragments#1]
Whenever using open with option when downloading a torrent file it does not work.
I believe it is because of the confinement strict, no access to /tmp, but is there any way to fix this problem ?

**Comment by ed10vi** [comment]
You are right, and it seems that there isn't a solution.
https://forum.snapcraft.io/t/accessing-tmp-from-snaps/22384

**Comment by soumyaDghosh** [comment]
This thing works with snaps like element, I guess it can be done, fragments actually open up but it doesn't get the magnet link.
